### ISSUE TITLE
[ENHANCEMENT] Extend Active Directory to return Manager property

### ISSUE THREAD

**Issue by stephenlane** [CSOIreland/Server-API-Library#10]
**Is your feature request related to a problem? Please describe.**
Need to identify users hierarchy so need to know who their manager is. Active directory is up to date so just need the manager property. 

**Describe the solution you'd like**
A users manager is returned as part of the active directory object.

**Comment by lorenzobruni** [comment]
@stephenlane Please follow the next steps to implement in the next release:

- Add the API_AD_CUSTOM_PROPERTIES key in all **Web.config** files and set your custom properties comas separated i.e. "_Manager, Other_"
```xml
<!-- Active Directory - Custom Properties (comas separated, case sensitive) -->
<add key="API_AD_CUSTOM_PROPERTIES" value="" />
```
- Implement your extended **UserPrincipal** query filter using the following template per each property you wish to add (i.e. Sample):
```c#
    [DirectoryRdnPrefix("CN")]
    [DirectoryObjectClass("Person")]
    public partial class UserPrincipalExtended : UserPrincipal
    {
        public UserPrincipalExtended(PrincipalContext context) : base(context) { }

        
        // Create the "Sample" property.    
        [DirectoryProperty("sample")]
        public string Sample
        {
            get
            {
                if (ExtensionGet("sample").Length != 1)
                    return string.Empty;

                return (string)ExtensionGet("sample")[0];
            }
            set { ExtensionSet("sample", value); }
        }
    }
```

- Just pass your type UserPrincipalExtended to the API.ActiveDirectory.Search() or API.ActiveDirectory.List(). If no type is passed, the default UserPrincipal type is used:
```c#
var userDetails = API.ActiveDirectory.Search<UserPrincipalExtended>("lanes");
var allDirectory = API.ActiveDirectory.List<UserPrincipalExtended>();
```
